In [12]:
import pandas as pd
import numpy as np
import re
import math
from collections import Counter

from numpy.linalg import norm

# NLP Bahasa Indonesia
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [13]:
df = pd.read_csv("D:\\Tugas Akhir\\sampel\\data\\scholar_articles_rows(1).csv")

df = df[['id', 'title', 'abstract']]
print("Jumlah dokumen:", len(df))
df.head()

Jumlah dokumen: 52

,id,title,abstract
0,1,pembuatan website sekolah menengah pertama neg...,… Praktik ini akan dilakukan pembuatan website...
1,2,Pembuatan Website Sebagai Media Promosi Yang T...,… pembuatan media promosi dan pemasaran berbas...
2,3,Otodidak Web Programming: Membuat Website Edut...,… Tahap Assembly adalah tahap pembuatan semua ...
3,4,Membuat website powerfull menggunakan PHP,… Hal yang perlu diperhatikan dalam pembuatan ...
4,5,Pembuatan Website Katalog Produk UMKM Untuk Pe...,"… perguruan tinggi, kami melakukan kegiatan pe..."

In [14]:
df_sample = df.head(10)
df_sample[['id', 'title', 'abstract']]

,id,title,abstract
0,1,pembuatan website sekolah menengah pertama neg...,… Praktik ini akan dilakukan pembuatan website...
1,2,Pembuatan Website Sebagai Media Promosi Yang T...,… pembuatan media promosi dan pemasaran berbas...
2,3,Otodidak Web Programming: Membuat Website Edut...,… Tahap Assembly adalah tahap pembuatan semua ...
3,4,Membuat website powerfull menggunakan PHP,… Hal yang perlu diperhatikan dalam pembuatan ...
4,5,Pembuatan Website Katalog Produk UMKM Untuk Pe...,"… perguruan tinggi, kami melakukan kegiatan pe..."
5,6,Pembuatan Website Profil Pada Sekolah Menengah...,… yang belum memiliki website dan dalam penyam...
6,7,Kiat jitu membuat website tanpa modal,"… website terhosting gratisan berjenis blog, m..."
7,8,Pembuatan Website Sebagai Sarana Promosi Pariw...,… Website merupakan salah satu sarana dalam me...
8,9,Pembuatan Website sebagai Media Pencitraan dan...,… dimanfaatkan secara efektif adalah pembuatan...
9,10,Pengembangan dan Pembuatan Website: Sebuah Tin...,… website harus melalui berbagai proses terleb...

In [15]:
stop_factory = StopWordRemoverFactory()
stopwords_id = set(stop_factory.get_stop_words())

stem_factory = StemmerFactory()
stemmer = stem_factory.create_stemmer()

In [16]:
def is_indonesian(text):
    tokens = text.split()
    indo_count = sum(1 for t in tokens if t in stopwords_id)
    return indo_count > 0

In [17]:
def preprocess_text(text):
    if pd.isna(text):
        return []

    # 1. Text Cleansing
    text = text.lower()
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    # 2. Tokenization
    tokens = text.split()

    # 3. Stopword Removal
    tokens = [t for t in tokens if t not in stopwords_id]

    # 4. Stemming (Bahasa Indonesia saja)
    if is_indonesian(text):
        tokens = [stemmer.stem(t) for t in tokens]

    return tokens

In [18]:
df['title_tokens'] = df['title'].apply(preprocess_text)
df['abstract_tokens'] = df['abstract'].apply(preprocess_text)

df[['id', 'title_tokens', 'abstract_tokens']]

,id,title_tokens,abstract_tokens
0,1,"[buat, website, sekolah, tengah, pertama, nege...","[praktik, laku, buat, website, sekolah, smp, n..."
1,2,"[buat, website, media, promosi, percaya]","[buat, media, promosi, pasar, bas, website, tu..."
2,3,"[otodidak, web, programming, membuat, website,...","[tahap, assembly, tahap, buat, semua, objek, b..."
3,4,"[membuat, website, powerfull, menggunakan, php]","[perlu, perhati, buat, web, kreatifitas, bangu..."
4,5,"[buat, website, katalog, produk, umkm, kembang...","[guru, tinggi, laku, giat, buat, website, medi..."
5,6,"[buat, website, profil, sekolah, tengah, perta...","[milik, website, sampai, informasi, perlu, bua..."
6,7,"[kiat, jitu, buat, website, modal]","[website, terhosting, gratis, jenis, blog, mul..."
7,8,"[buat, website, sarana, promosi, pariwisata, s...","[website, rupa, salah, satu, sarana, promosi, ..."
8,9,"[buat, website, media, citra, promosi, desa, k...","[manfaat, efektif, buat, website, desa, websit..."
9,10,"[kembang, buat, website, buah, tinjau, literatur]","[website, lalu, bagai, proses, lebih, jadi, bu..."
10,11,"[otodidak, web, programming, membuat, website,...","[tahap, assembly, tahap, buat, semua, objek, b..."
11,12,"[membuat, website, powerfull, menggunakan, php]","[perlu, perhati, buat, web, kreatifitas, bangu..."
12,13,"[kiat, jitu, buat, website, modal]","[website, terhosting, gratis, jenis, blog, mul..."
13,14,"[buat, website, e, commerce, distro, java, trend]","[the, purpose, of, this, project, is, to, buil..."
14,15,"[latih, desain, buat, website, pt, abisakti, s...","[metode, latih, buat, website, buat, website, ..."
15,16,"[buat, website, sarana, promosi, produk, kelom...","[lebih, efisien, hal, buat, website, pidra, we..."
16,17,"[buat, website, guna, visual, studio, code, sm...","[tema, latih, buat, website, guna, visual, stu..."
17,18,"[langkah, praktis, membuat, website, gratis]","[walaupun, bab, bahas, siap, buat, website, sa..."
18,19,"[latih, buat, website, portal, guna, wordpress...","[cms, rupa, alternatif, buat, website, beri, l..."
19,20,"[gampang, gratis, buat, website, web, personal...","[buah, website, website, website, bukan, jadi,..."
20,21,"[otodidak, web, programming, membuat, website,...","[tahap, assembly, tahap, buat, semua, objek, b..."
21,22,"[membuat, website, powerfull, menggunakan, php]","[perlu, perhati, buat, web, kreatifitas, bangu..."
22,23,"[kiat, jitu, buat, website, modal]","[website, terhosting, gratis, jenis, blog, mul..."
23,24,"[langkah, praktis, membuat, website, gratis]","[walaupun, bab, bahas, siap, buat, website, sa..."
24,25,"[gampang, gratis, buat, website, web, personal...","[buah, website, website, website, bukan, jadi,..."
25,26,"[pembuatan, website, tempat, pariwisata, rumah...","[teliti, tulis, batas, masalah, buat, website,..."
26,27,"[pembuatan, website, profil, sekolah, dasar, n...","[santoso, bahas, buat, web, profil, roso, budh..."
27,28,"[damping, buat, website, desa, gunung, malelo,...","[buat, website, desa, jadi, solusi, tepat, ata..."
28,29,"[pembuatan, website, desa, wisata, kabupaten, ...","[uji, website, hindar, ada, bug, sistem, buat,..."
29,30,"[pembuatan, website, desa, buaran, mayong, jep...","[dosen, bimbing, beri, bantu, buat, website, l..."
30,31,"[ancang, buat, website, jual, biji, kopi, soci...","[sama, sekali, milik, website, kafe, ancang, b..."
31,32,"[buat, website, company, profile, konoba, coff...","[buat, website, company, profile, konoba, coff..."
32,33,"[buat, website, sekolah, media, informasi, pro...","[buat, website, tahap, laksana, tim, abdi, bua..."
33,34,"[buat, website, php, codeigniter]","[codeigniter, framework, php, guna, sederhana,..."
34,35,"[latih, buat, website, wix, umkm]","[tahu, umkm, rancang, website, usaha, cara, bu..."
35,36,"[pembuatan, website, profil, sekolah, menengah...","[kerja, praktik, buat, website, profil, sekola..."
36,37,"[tingkat, digitalisasi, lalu, buat, website, t...","[website, sekolah, giat, abdi, masyarakat, bas..."
37,38,"[pembuatan, website, arsyla, catering]","[informasi, buat, website, guna, xampp, mysql,..."
38,39,"[pembuatan, website, sistem, informasi, objek,...","[buat, website, guna, dekat, object, lihat, we..."
39,40,"[latih, buat, website, hadap, kembang, teknolo...","[butuh, bidang, buat, website, butuh, buat, we..."
40,41,"[latih, buat, website, desa, wisata, desa, wis...","[fokus, latih, pembutan, website, desa, atas, ..."
41,42,"[latih, buat, website, guna, html, css]","[buah, latih, buat, website, guna, html, sanga..."
42,43,"[ancang, buat, website, sosial, media, desa, w...","[wisata, angsana, langsung, buat, website, med..."
43,44,"[pembuatan, website, informasi, pendaftaran, w...","[buat, website, php, rupa, salah, satu, metode..."
44,45,"[merancang, membuat, website]","[buat, website, helm, sni, online, website, pa..."
45,46,"[buat, website, komunitas, ppkm]","[the, purpose, of, this, thesis, is, making, a..."
46,47,"[pembuatan, website, profil, sekolah, menengah...","[a, website, for, website, that, profiles, www..."
47,48,"[guna, user, centered, design, buat, website, ...","[portal, website, mudah, proses, bisnis, organ..."
48,49,"[implementasi, web, development, life, cycle, ...","[website, development, life, cycle, wdlc, pili..."
49,50,"[buat, website, media, promosi, wisata, pulau,...","[utilizing, a, website, as, a, promotional, me..."
50,51,"[latih, buat, website, digital, marketing, goo...","[damping, buat, website, sederhana, buat, webs..."
51,52,"[latih, buat, website, profile, ternak, ikan, ...","[website, metode, pkm, laku, cara, latih, mula..."

In [19]:
all_tokens = []
for tokens in df['title_tokens'].tolist() + df['abstract_tokens'].tolist():
    all_tokens.extend(tokens)

vocab = sorted(set(all_tokens))
len(vocab)

451

In [20]:
def compute_tf(tokens):
    tf = {}
    total = len(tokens)
    counter = Counter(tokens)

    for term, freq in counter.items():
        tf[term] = freq / total

    return tf

In [21]:
df['tf_title'] = df['title_tokens'].apply(compute_tf)
df['tf_abstract'] = df['abstract_tokens'].apply(compute_tf)

In [22]:
N = len(df)
documents = df['title_tokens'].tolist() + df['abstract_tokens'].tolist()

idf = {}
for term in vocab:
    df_t = sum(1 for doc in documents if term in doc)
    idf[term] = math.log10(N / df_t) if df_t > 0 else 0

In [23]:
def compute_tfidf(tf, idf, vocab):
    return np.array([tf.get(term, 0) * idf[term] for term in vocab])

In [24]:
df['tfidf_title'] = df['tf_title'].apply(lambda x: compute_tfidf(x, idf, vocab))
df['tfidf_abstract'] = df['tf_abstract'].apply(lambda x: compute_tfidf(x, idf, vocab))